# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='listText',
            field=models.CharField(max_length=200),
        ),
    ]
